### ISSUE TITLE
Page content will be skipped with <div /> convention.

### ISSUE THREAD

**Issue by Spansky** [Pixboost/pixboost-js#19]
In your documentation (https://help.pixboost.com/web-dom/responsive-images) you have following snippet.

Not working
```
<div data-pb-picture
    data-url="https://yoursite.com/doggy.png"
    ... blablabla />
```
I tried this out in my website directly. I replaced ```<p><img ...></p>``` with ```<p><div... /></p>```
Unfortunately your javascript will then exclude the remaining content. 
[Test-Blogarticle](https://www.magicpony.de/travel/2000/01/01/Testing-for-Dimitry.html)

^^You can check on my testsystem how this issue looks like. If you check the sourcecode you will see the full content. After your JS is executed, most of the source will be ignored by Firefox and Google Chrome. 

Workaround:
```
<div data-pb-picture
    data-url="https://yoursite.com/doggy.png"
    ... blablabla ></div>
```

**Comment by dooman87** [comment]
Hi @Spansky ,

Thanks a lot for opening the issue. There is a bug in documentation that I fixed already.

Divs tags should be closed with </div>. In your example replace `/>` on `data-pb-picture` divs with `></div>`:

```html
<div data-pb-picture data-url="https://www.magicpony.de//assets/a42c862613ef4dc58baa049e33f28db7.png" data-lg="optimise" data-md="resize?size=600" data-sm="resize?size=500"></div>
```

Let me know if that worked and I'll close the ticket then

**Comment by Spansky** [comment]
Yes. It works fine :) Thank you!
